Popular page
LorePetriella/movies pull request #11
Opened 2023-03-01 02:57 UTC by LorePetriella

2023-03-04 23:30 UTC, adrianmdp requested changes

2023-03-04 23:30 UTC, adrianmdp commented on src/pages/popular/index.tsx
> +      .get("/movie/popular")
Aca pasa lo mismo que en search. No me gusta que el endpoint lo pase el componente.
Esto se debe a que si en algún momento hay algun cambio en la api y los endpoints son diferentes, tendríamos que ir a modificar todos los componentes donde quisimos obtener las movies "popular".
Si vos haces un ServicesMovies.getPopular(...) el día de mañana no importa los cambios que haya más allá del componente, siempre te va a funcionar.

2023-03-05 17:14 UTC, LorePetriella commented on src/pages/popular/index.tsx
> +      .get("/movie/popular")
Subí los cambios en los servicios

2023-03-09 02:16 UTC, adrianmdp approved these changes

2023-03-11 22:39 UTC, merged