Upcoming page
LorePetriella/movies pull request #12
Opened 2023-03-01 03:21 UTC by LorePetriella

2023-03-04 23:35 UTC, adrianmdp requested changes

2023-03-04 23:35 UTC, adrianmdp commented on src/pages/upcoming/index.tsx
> +      .get("/movie/upcoming")
Mismo caso que en la PR anterior.

2023-03-04 23:35 UTC, adrianmdp commented on src/pages/popular/index.tsx
> +      .get("/movie/popular")
Mismo caso que en la PR anterior.

2023-03-04 23:43 UTC, adrianmdp requested changes
Al corregir los errores de la PR anterior, esta estaría aprobada.

2023-03-05 17:47 UTC, LorePetriella commented on src/pages/upcoming/index.tsx
> +      .get("/movie/upcoming")
Listo el cambio

2023-03-09 02:18 UTC, adrianmdp approved these changes

2023-03-11 22:42 UTC, merged